QuizWebApp/ViewModels/AnswerViewModel.cs
using Core.Common;

namespace QuizWebApp.ViewModels
{
    public class AnswerViewModel
    {
        public long Id { get; set; }
        public string? Name { get; set; }
        public string? Description { get; set; }
        public Status Status { get; set; }
        public long QuestionId { get; set; }
        public string? Image { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}

QuizWebApp/Controllers/AnswerController.cs
using Microsoft.AspNetCore.Mvc;
using QuizWebApp.Providers;
using QuizWebApp.Services;
using QuizWebApp.ViewModels;

namespace QuizWebApp.Controllers
{
    public class AnswerController : BaseController
    {
        private readonly ILoggerManager _loggerManager;
        private readonly QuizService _quizService;
        public AnswerController(ILoggerManager loggerManager, IQuizService quizService)
        {
            _loggerManager = loggerManager;
            _quizService = (QuizService)quizService;
        }

        public IActionResult Index()
        {
            try
            {
                var answerList = _quizService.GetAnswerList();
                return View(answerList);
            }
            catch (Exception ex)
            {
                _loggerManager.LogError(ex.ToString());
                return NotFound();
            }
        }

        public IActionResult CreateEditAnswer(long? id)
        {
            try
            {
                AnswerViewModel answer;
                ViewData["Questions"] = _quizService.GetQuestionList();

                if (id != null && id != 0)
                {
                    ViewData["Title"] = "Update Answer";
                    answer = _quizService!.GetAnswerById((long)id)!;
                }
                else
                {
                    ViewData["Title"] = "Create New Answer";
                    answer = new AnswerViewModel();
                }

                return View(answer);
            }
            catch (Exception ex)
            {
                _loggerManager.LogError(ex.ToString());
                return NotFound();
            }
        }

        [HttpPost]
        public IActionResult CreateEditAnswer(AnswerViewModel answerViewModel, IFormFile? Image)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _quizService.CreateUpdateAnswer(answerViewModel, _userLogin, Image);
                    return Redirect("/answer");
                }

                ViewData["Title"] = "Create New Answer";
                ViewData["Questions"] = _quizService.GetQuestionList();
                return View(answerViewModel);
            }
            catch (Exception ex)
            {
                _loggerManager.LogError(ex.ToString());
                return NotFound();
            }
        }

        [HttpPost]
        public JsonResult DeleteAnswer(int id)
        {
            try
            {
                return _quizService.DeleteAnswer(id);
            }
            catch (Exception ex)
            {
                _loggerManager.LogError(ex.ToString());
                return new JsonResult("Error");
            }
            
        }

        [HttpPost]
        public IActionResult ExportExcelAnswer()
        {
            try
            {
                var questionList = _quizService.GetAnswerList();

                byte[] file = questionList.ExportExcel<AnswerViewModel>();
                return File(file, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "answer.xlsx");
            }
            catch (Exception ex)
            {
                _loggerManager.LogError(ex.ToString());
                return NotFound();
            }
        }

        [HttpPost]
        public IActionResult ImportExcelAnswer(IFormFile ExcelAnswerFile)
        {
            try
            {
                if (ExcelAnswerFile != null)
                {
                    if (ExcelAnswerFile.ContentType == "application/vnd.ms-excel" || ExcelAnswerFile.ContentType == "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
                    {
                        _quizService.ImportExcelAnswer(ExcelAnswerFile, _userLogin);
                        return Redirect("/answer");
                    }
                    else
                    {
                        ModelState.AddModelError("File", "Unable to Upload file!");
                        return View();
                    }
                }
                else
                {
                    ModelState.AddModelError("File", "Unable to Upload file!");
                    return View();
                }
            }
            catch (Exception ex)
            {
                _loggerManager.LogError(ex.ToString());
                return NotFound();
            }
        }
    }
}

QuizWebApp/Views/Answer/CreateEditAnswer.cshtml
@model QuizWebApp.ViewModels.AnswerViewModel
@using Core.Common;
@using QuizWebApp.ViewModels;

@{
    var questions = ViewData["Questions"] as IEnumerable<QuestionViewModel>;
}

<div>
    <div class="text-center mb-3">
       <h1 class="display-4">@ViewData["Title"]</h1>
    </div>
    <div class="p-4 border w-100">
        <form method="post" asp-controller="Answer" asp-action="CreateEditAnswer" enctype="multipart/form-data" id="create-update-answer-form">
            <div class="row w-100 mb-3">
            <div class="col-md-6 col-12">
                <div class="form-group row pe-md-5 mb-3">
                    <label for="inputName" class="col-sm-2 col-form-label">Name</label>
                    <div class="col-sm-10">
                      <input type="text" class="form-control" id="inputName" asp-for="Name">
                      <span class="error" asp-validation-for="Name"></span>
                    </div>
                </div>
                <input type="hidden" class="form-control" asp-for="Id">
                <input type="hidden" class="form-control" asp-for="Image">

                <div class="form-group pe-md-5 row mb-3">
                    <label for="inputQuestion" class="col-sm-2 col-form-label">Category</label>
                    <div class="col-sm-10">
                        <select id="inputQuestion" class="form-control" asp-for="QuestionId">
                            @foreach(var question in questions!)
                            {
                                <option value="@question.Id">@question.Id - @question.Name</option>
                            }
                        </select>
                        <span class="error" asp-validation-for="QuestionId"></span>
                    </div>
                </div>

            </div>

            <div class="col-md-6 col-12 pe-md-5">

                <div class="form-group row mb-3">
                    <label for="inputStatus" class="col-sm-2 col-form-label">Status</label>
                    <div class="col-sm-10">
                        <select id="inputStatus" class="form-control" asp-for="Status" asp-items="Html.GetEnumSelectList<Status>()">
                        </select>
                    </div>
                </div>

                <div class="form-group row mb-3">
                    <label for="inputName" class="col-sm-2 col-form-label">Image</label>
                    <div class="col-sm-10">
                      <input onchange="readURL(this);" type="file" accept=".jpg,.png,.jpeg" class="form-control" id="inputImage" asp-for="Image">
                    </div>
                </div>

                <div class="mb-3 w-100 d-flex justify-content-center">
                    <div class="w-50 d-flex justify-content-center">
                       @if (String.IsNullOrEmpty(Model.Image))
                       {
                          <img class="img-fluid border cursor-pointer img-question" src="~/images/choose-img.png" id="answer-img"/>
                       }
                       else
                       {
                           <img class="img-fluid border cursor-pointer img-question" src="~/images/@Model.Image" id="answer-img"/>  
                       }
                    </div>
                </div>

            </div>
        </div>
        <div class="row w-100 pe-md-5 mb-3">
            <div class="form-group pe-0">
                <label for="descriptionInput">Description</label>
                <textarea class="form-control w-100" id="descriptionInput" rows="6" asp-for="Description"></textarea>
                <span class="error" asp-validation-for="Description"></span>
            </div>
        </div>

        <div class="w-100 d-flex justify-content-center">
            <div>
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="/answer" class="btn btn-secondary ms-4">Cancel</a>
            </div>
        </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        $( "#answer-img" ).click(function() {
            $("#inputImage").click();
        });

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#answer-img')
                        .attr('src', e.target.result);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }

    </script>
}

QuizWebApp/Views/Answer/Index.cshtml
@model IEnumerable<QuizWebApp.ViewModels.AnswerViewModel>
@using Core.Common;

@{
    ViewData["Title"] = "Answer Page";
}

<div>
    <div class="text-center">
       <h1 class="display-4">Answer List</h1>
    </div>

    <div class="ms-4 my-3">
        <a href="/answer/create" class="btn btn-success">Add Answer</a>
        <form class="m-0 p-0 d-inline-block" method="post" asp-controller="Answer" asp-action="ExportExcelAnswer">
            <button type="submit" class="btn btn-success ms-4">Export Answer</button>
        </form>
        <form class="mx-5 p-0 d-inline-block" id="import-answer-form" method="post" asp-controller="Answer" asp-action="ImportExcelAnswer" enctype="multipart/form-data">
            <input type="file" accept=".xlsx" name="ExcelAnswerFile"/>
            <button type="submit" class="btn btn-success ms-4">Import Answer</button>
        </form>
    </div>

    <div>
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Name</th>
              <th scope="col">Description</th>
              <th scope="col">Question</th>
              <th scope="col">Image</th>
              <th scope="col">Status</th>
              <th scope="col"></th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>

            @foreach(var answer in Model)
            {
            <tr>
                <th scope="row">@answer.Id</th>
                <td>@answer.Name</td>
                <td>@answer.Description</td>
                <td>@answer.QuestionId</td>
                <td>
                    @if (!String.IsNullOrEmpty(answer.Image))
                    {
                       <img class="img-item" src="~/images/@answer.Image"/>
                    }
                </td>
                <td>@Enum.GetName(typeof(Status), answer.Status)</td>
                <td><a href="/answer/update/@answer.Id" class="btn btn-primary">Edit</a></td>
                <td><button onclick="confirmDeleteAnswer(@answer.Id)" type="button" class="btn btn-danger">Delete</button></td>
            </tr>
            }
          </tbody>
        </table>
    </div>
</div>

@section Scripts {
    <script>
        function confirmDeleteAnswer(answerId)
        {
            swal({
              title: "Are you sure?",
              text: "Do you want to delete this answer?",
              icon: "warning",
              buttons: true,
              dangerMode: true,
            })
            .then((willDelete) => {
              if (willDelete) {
                  deleteAnswer(answerId);
              }
            });
        }

        function deleteAnswer(answerId) {
            $.ajax({
                url: "/Answer/DeleteAnswer/" + answerId,
                type: "POST",
                success: function (data) {
                    window.location="/answer";
                }
            });
        }

        var importAnswerForm = {};
        // Form initialisation
        importAnswerForm.init = function () {
            // Validate For Registration
            $('#import-answer-form').validate({
                highlight: function (element, errorClass, validClass) {
                    if ($(element).attr("type") === "radio") {
                        this.findByName(element.name).addClass(errorClass);
                    } else {
                        $(element).addClass(errorClass);
                    }
                },
                unhighlight: function (element, errorClass, validClass) {
                    if ($(element).attr("type") === "radio") {
                        this.findByName(element.name).removeClass(errorClass);
                    } else {
                        $(element).removeClass(errorClass);
                    }
                },
                rules: {
                    ExcelAnswerFile: {
                        required: true
                    }
                },
                messages: {
                    ExcelAnswerFile: {
                        required: "File Import is required"
                    }
                }
            });

        };

        $(importAnswerForm.init);
        
    </script>
}