QuizWebApp/ViewModels/CategoryViewModel.cs
using Core.Common;
using System.ComponentModel.DataAnnotations;

namespace QuizWebApp.ViewModels
{
    public class CategoryViewModel
    {
        public long Id { get; set; }
        [Required]
        public Status Status { get; set; }
        [Required]
        public string? Name { get; set; }
        [Required]
        public string? Description { get; set; }
        public string? Icon { get; set; }
        public long ParentId { get; set; }
    }
}

QuizWebApp/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using QuizWebApp.Providers;
using QuizWebApp.Services;
using QuizWebApp.ViewModels;

namespace QuizWebApp.Controllers
{
    #pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
    public class CategoryController : BaseController
    {
        private readonly ILoggerManager _loggerManager;
        private readonly QuizService _quizService;
        public CategoryController(ILoggerManager logger, IQuizService quizService)
        {
            _loggerManager = logger;
            _quizService = (QuizService)quizService;
        }

        public IActionResult CreateEditCategory(long? id)
        {
            try
            {
                CategoryViewModel category;

                if (id != null && id != 0)
                {
                    ViewData["Title"] = "Update Category";
                    category = _quizService.GetCategoryById((long)id);
                }
                else
                {
                    ViewData["Title"] = "Create New Category";
                    category = new CategoryViewModel();
                }

                return View(category);
            }
            catch (Exception ex)
            {
                _loggerManager.LogError(ex.ToString());
                return NotFound();
            }
        }

        [HttpPost]
        public IActionResult CreateEditCategory(CategoryViewModel categoryViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _quizService.CreateUpdateCategory(categoryViewModel, _userLogin);
                    return Redirect("/category");
                }

                ViewData["Title"] = "Create New Category";
                return View(categoryViewModel);
            }
            catch (Exception ex)
            {
                _loggerManager.LogError(ex.ToString());
                return NotFound();
            }
        }

        [HttpPost]
        public JsonResult DeleteCategory(int id)
        {
            try
            {
                return _quizService.DeleteCategory(id);
            }
            catch (Exception ex)
            {
                _loggerManager.LogError(ex.ToString());
                return new JsonResult("Error");
            }
        }
    }
}

QuizWebApp/Views/Category/CreateEditCategory.cshtml
@model QuizWebApp.ViewModels.CategoryViewModel
@using Core.Common;
@using QuizWebApp.ViewModels;

<div>
    <div class="text-center mb-3">
       <h1 class="display-4">@ViewData["Title"]</h1>
    </div>
    <div class="p-4 border w-100">
        <form method="post" asp-controller="Category" asp-action="CreateEditCategory" id="create-update-category-form">
            <div class="row w-100 mb-3">
            <div class="col-md-6 col-12">
                <div class="form-group row pe-md-5 mb-3">
                    <label for="inputName" class="col-sm-2 col-form-label">Name</label>
                    <div class="col-sm-10">
                      <input type="text" class="form-control" id="inputName" asp-for="Name">
                      <span class="error" asp-validation-for="Name"></span>
                    </div>
                </div>
                <input type="hidden" class="form-control" asp-for="Id">
            </div>

            <div class="col-md-6 col-12 pe-md-5">

                <div class="form-group row mb-3">
                    <label for="inputStatus" class="col-sm-2 col-form-label">Status</label>
                    <div class="col-sm-10">
                        <select id="inputStatus" class="form-control" asp-for="Status" asp-items="Html.GetEnumSelectList<Status>()">
                        </select>
                        <span class="error" asp-validation-for="Status"></span>
                    </div>
                </div>

            </div>
        </div>
        <div class="row w-100 pe-md-5 mb-3">
            <div class="form-group pe-0">
                <label for="descriptionInput">Description</label>
                <textarea class="form-control w-100" id="descriptionInput" rows="3" asp-for="Description"></textarea>
                <span class="error" asp-validation-for="Description"></span>
            </div>
        </div>

        <div class="w-100 d-flex justify-content-center">
            <div>
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="/category" class="btn btn-secondary ms-4">Cancel</a>
            </div>
        </div>
        </form>
    </div>
</div>