QuizWebApp/ViewModels/QuestionViewModel.cs
using Core.Common;
using System.ComponentModel.DataAnnotations;

namespace QuizWebApp.ViewModels
{
    public class QuestionViewModel
    {
        public long Id { get; set; }
        [Required]
        public Status Status { get; set; }
        [Required]
        public string? Name { get; set; }
        [Required]
        public string? Description { get; set; }
        public string? Image { get; set; }
        [Required]
        public byte Level { get; set; }
        [Required]
        public QuestionType Type { get; set; }
        [Required]
        public long CategoryId { get; set; }
        public string? CategoryName { get; set; }
    }
}

QuizWebApp/Controllers/QuestionController.cs
using Microsoft.AspNetCore.Mvc;
using QuizWebApp.Providers;
using QuizWebApp.Services;
using QuizWebApp.ViewModels;

namespace QuizWebApp.Controllers
{
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.

    public class QuestionController : BaseController
    {
        private readonly ILoggerManager _loggerManager;
        private readonly QuizService _quizService;
        public QuestionController(ILoggerManager logger, IQuizService quizService)
        {
            _loggerManager = logger;
            _quizService = (QuizService)quizService;
        }

        public IActionResult Index()
        {
            try
            {
                var questionList = _quizService.GetQuestionList();
                return View(questionList);
            }
            catch (Exception ex)
            {
                _loggerManager.LogError(ex.ToString());
                return NotFound();
            }
        }

        public IActionResult CreateEditQuestion(long? id)
        {
            try
            {
                QuestionViewModel question;
                ViewData["Categories"] = _quizService.GetCategoryList();

                if (id != null && id != 0)
                {
                    ViewData["Title"] = "Update Question";
                    question = _quizService.GetQuestionById((long)id);
                }
                else
                {
                    ViewData["Title"] = "Create New Question";
                    question = new QuestionViewModel();
                }

                return View(question);
            }
            catch (Exception ex)
            {
                _loggerManager.LogError(ex.ToString());
                return NotFound();
            }
        }

        [HttpPost]
        public IActionResult CreateEditQuestion(QuestionViewModel questionViewModel, IFormFile? Image)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _quizService.CreateUpdateQuestion(questionViewModel, _userLogin, Image);
                    return Redirect("/question");
                }

                ViewData["Title"] = "Create New Question";
                ViewData["Categories"] = _quizService.GetCategoryList();
                return View(questionViewModel);
            }
            catch (Exception ex)
            {
                _loggerManager.LogError(ex.ToString());
                return NotFound();
            }
        }

        [HttpPost]
        public JsonResult DeleteQuestion(int id)
        {
            try
            {
                return _quizService.DeleteQuestion(id);
            }
            catch (Exception ex)
            {
                _loggerManager.LogError(ex.ToString());
                return new JsonResult("Error");
            }
        }

        [HttpPost]
        public IActionResult ExportExcelQuestion()
        {
            try
            {
                var questionList = _quizService.GetQuestionList();
                byte[] file = questionList.ExportExcel<QuestionViewModel>();

                return File(file, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "question.xlsx");
            }
            catch (Exception ex)
            {
                _loggerManager.LogError(ex.ToString());
                return NotFound();
            }
        }

        [HttpPost]
        public IActionResult ImportExcelQuestion(IFormFile ExcelQuestionFile)
        {
            try
            {
                if (ExcelQuestionFile != null)
                {
                    if (ExcelQuestionFile.ContentType == "application/vnd.ms-excel" || ExcelQuestionFile.ContentType == "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
                    {
                        _quizService.ImportExcelQuestion(ExcelQuestionFile, _userLogin);
                        return Redirect("/question");
                    }
                    else
                    {
                        ModelState.AddModelError("File", "Unable to Upload file!");
                        return View();
                    }
                }
                else
                {
                    ModelState.AddModelError("File", "Unable to Upload file!");
                    return View();
                }
            }
            catch (Exception ex)
            {
                _loggerManager.LogError(ex.ToString());
                return NotFound();
            }
        }

    }
}

QuizWebApp/Views/Question/CreateEditQuestion.cshtml
@model QuizWebApp.ViewModels.QuestionViewModel
@using Core.Common;
@using QuizWebApp.ViewModels;

@{
    var categories = ViewData["Categories"] as IEnumerable<CategoryViewModel>;
}

<div>
    <div class="text-center mb-3">
       <h1 class="display-4">@ViewData["Title"]</h1>
    </div>
    <div class="p-4 border w-100">
        <form method="post" asp-controller="Question" asp-action="CreateEditQuestion" enctype="multipart/form-data" id="create-update-question-form">
            <div class="row w-100 mb-3">
            <div class="col-md-6 col-12">
                <div class="form-group row pe-md-5 mb-3">
                    <label for="inputName" class="col-sm-2 col-form-label">Name</label>
                    <div class="col-sm-10">
                      <input type="text" class="form-control" id="inputName" asp-for="Name">
                      <span class="error" asp-validation-for="Name"></span>
                    </div>
                </div>
                <input type="hidden" class="form-control" asp-for="Id">
                <input type="hidden" class="form-control" asp-for="Image">
                <div class="form-group row pe-md-5 mb-3">
                    <label for="inputLevel" class="col-sm-2 col-form-label">Level</label>
                    <div class="col-sm-10">
                      <input type="number" class="form-control" id="inputLevel" asp-for="Level">
                    </div>
                </div>

                <div class="form-group row pe-md-5 mb-3">
                    <label for="inputType" class="col-sm-2 col-form-label">Type</label>
                    <div class="col-sm-10">
                        <select id="inputType" class="form-control" asp-for="Type" asp-items="Html.GetEnumSelectList<QuestionType>()">
                        </select>
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-12 pe-md-5">
                <div class="form-group row mb-3">
                    <label for="inputCategory" class="col-sm-2 col-form-label">Category</label>
                    <div class="col-sm-10">

                        <select id="inputCategory" class="form-control" asp-for="CategoryId">
                            @foreach(var category in categories!)
                            {
                                <option value="@category.Id">@category.Name</option>
                            }
                        </select>
                    </div>
                </div>

                <div class="form-group row mb-3">
                    <label for="inputStatus" class="col-sm-2 col-form-label">Status</label>
                    <div class="col-sm-10">
                        <select id="inputStatus" class="form-control" asp-for="Status" asp-items="Html.GetEnumSelectList<Status>()">
                        </select>
                    </div>
                </div>

                <div class="form-group row mb-3">
                    <label for="inputName" class="col-sm-2 col-form-label">Image</label>
                    <div class="col-sm-10">
                      <input onchange="readURL(this);" type="file" accept=".jpg,.png,.jpeg" class="form-control" id="inputImage" asp-for="Image">
                    </div>
                </div>

                <div class="mb-3 w-100 d-flex justify-content-center">
                    <div class="w-50 d-flex justify-content-center">
                       @if (String.IsNullOrEmpty(Model.Image))
                       {
                          <img class="img-fluid border cursor-pointer img-question" src="~/images/choose-img.png" id="question-img"/>
                       }
                       else
                       {
                           <img class="img-fluid border cursor-pointer img-question" src="~/images/@Model.Image" id="question-img"/>  
                       }
                    </div>
                </div>

            </div>
        </div>
        <div class="row w-100 pe-md-5 mb-3">
            <div class="form-group pe-0">
                <label for="descriptionInput">Description</label>
                <textarea class="form-control w-100" id="descriptionInput" rows="6" asp-for="Description"></textarea>
                <span class="error" asp-validation-for="Description"></span>
            </div>
        </div>

        <div class="w-100 d-flex justify-content-center">
            <div>
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="/question" class="btn btn-secondary ms-4">Cancel</a>
            </div>
        </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        $( "#question-img" ).click(function() {
            $("#inputImage").click();
        });

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#question-img')
                        .attr('src', e.target.result);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }

    </script>
}

QuizWebApp/Views/Question/Index.cshtml
@model IEnumerable<QuizWebApp.ViewModels.QuestionViewModel>
@using Core.Common;

@{
    ViewData["Title"] = "Question Page";
}

<div>
    <div class="text-center">
       <h1 class="display-4">Question List</h1>
    </div>
    
    <div class="ms-4 my-3">
        <a href="/question/create" class="btn btn-success">Add Question</a>
        <form class="m-0 p-0 d-inline-block" method="post" asp-controller="Question" asp-action="ExportExcelQuestion">
            <button type="submit" class="btn btn-success ms-4">Export Question</button>
        </form>
        <form class="mx-5 p-0 d-inline-block" id="import-question-form" method="post" asp-controller="Question" asp-action="ImportExcelQuestion" enctype="multipart/form-data">
            <input type="file" accept=".xlsx" name="ExcelQuestionFile"/>
            <button type="submit" class="btn btn-success ms-4">Import Question</button>
        </form>
    </div>
    
    <div>
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Name</th>
              <th scope="col">Description</th>
              <th scope="col">Type</th>
              <th scope="col">Image</th>
              <th scope="col">Category</th>
              <th scope="col">Status</th>
              <th scope="col"></th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>

            @foreach(var question in Model)
            {
            <tr>
                <th scope="row">@question.Id</th>
                <td>@question.Name</td>
                <td>@question.Description</td>
                <td>@Enum.GetName(typeof(QuestionType), question.Type)</td>
                <td>
                    @if (!String.IsNullOrEmpty(question.Image))
                    {
                       <img class="img-item" src="~/images/@question.Image"/>
                    }
                </td>
                <td>@question.CategoryName</td>
                <td>@Enum.GetName(typeof(Status), question.Status)</td>
                <td><a href="/question/update/@question.Id" class="btn btn-primary">Edit</a></td>
                <td><button onclick="confirmDeleteQuestion(@question.Id)" type="button" class="btn btn-danger">Delete</button></td>
            </tr>
            }
          </tbody>
        </table>
    </div>
</div>

@section Scripts {
    <script>
        function confirmDeleteQuestion(questionId)
        {
            swal({
              title: "Are you sure?",
              text: "Do you want to delete this question?",
              icon: "warning",
              buttons: true,
              dangerMode: true,
            })
            .then((willDelete) => {
              if (willDelete) {
                  deleteQuestion(questionId);
              }
            });
        }

        function deleteQuestion(questionId) {
            $.ajax({
                url: "/Question/DeleteQuestion/" + questionId,
                type: "POST",
                success: function (data) {
                    //swal("Question has been deleted!", {
                    //    icon: "success",
                    //});
                    window.location="/question";
                }
            });
        }

        var importQuestionForm = {};
        // Form initialisation
        importQuestionForm.init = function () {
            // Validate For Registration
            $('#import-question-form').validate({
                highlight: function (element, errorClass, validClass) {
                    if ($(element).attr("type") === "radio") {
                        this.findByName(element.name).addClass(errorClass);
                    } else {
                        $(element).addClass(errorClass);
                    }
                },
                unhighlight: function (element, errorClass, validClass) {
                    if ($(element).attr("type") === "radio") {
                        this.findByName(element.name).removeClass(errorClass);
                    } else {
                        $(element).removeClass(errorClass);
                    }
                },
                rules: {
                    ExcelQuestionFile: {
                        required: true
                    }
                },
                messages: {
                    ExcelQuestionFile: {
                        required: "File Import is required"
                    }
                }
            });

        };

        $(importQuestionForm.init);
        
    </script>
}